### PR TITLE
Fix Franchise Module and Controller issues

### LINKED ISSUE #14: Franchise Module

### LINKED ISSUE #15: Franchise Controller

### PR DESCRIPTION
**Pull request by ballyalley-o**
This pull request fixes the following issues:

- Issue #14: Franchise Module

- Issue #15: Franchise Controller

The changes include:

- Adding the FRANCHISE directory path to the PATH_DIR object in the config/path-dir.ts file.

- Adding the FRANCHISE tag to the TAGS object in the constant/tag.ts file.

- Adding the createFranchiseHistory method to the SDKSetController class in the controller/sdk-set.ts file.

- Adding the Franchise model and schema to the codebase.

- Updating the Franchise ownership field to be an array.

- Adding a new franchise route and controller for creating franchise history.

These changes enhance the codebase by providing a standardized way to handle franchise-related operations, improving the functionality and readability of the application.

### CODE REVIEW

File: controller/sdk-set.ts [hunk 1]
```diff
@@ -55,6 +53,76 @@ class SDKSetController {
...
+      }
+
+      const finalTeamHistories = Object.values(teamHistoriesByTeamId).map((histories) => {
+        if (histories.length === 1) {
+          return histories[0]
+        }
+
+        histories.sort((a, b) => b.years - a.years)
+        const mainHistory = histories[0]
+        mainHistory.teamHistory = histories.slice(1)
```
Comment (in-a-iii) [inline controller/sdk-set.ts:111]: this will not be an objectId, but i think this will work better. Change the type in the interface.

File: typings/model.d.ts [hunk 2]
```diff
@@ -133,6 +133,31 @@ declare interface Foul {
...
+  years: number
+  games: number
+  wins: number
+  losses: number
+  winPercentage: number
+  playoffAppearances: number
+  divisionTitles: number
+  conferenceTitles: number
+  championships: number
+  teamHistory: Schema.Types.ObjectId[]
```
Comment (in-a-iii) [inline typings/model.d.ts]: Change this to an Object array. instead of ObjectId, we'll reference the main if needed.

**Review by in-a-iii — CHANGES_REQUESTED** [review]

File: controller/sdk-set.ts (hunk 1 above)
Comment (ballyalley-o) [reply controller/sdk-set.ts:111]: Yeah, thought about that.

File: typings/model.d.ts (hunk 2 above)
Comment (ballyalley-o) [reply typings/model.d.ts]: will do..

File: typings/model.d.ts [hunk 3]
```diff
@@ -154,7 +154,7 @@ interface Franchise {
   divisionTitles: number
   conferenceTitles: number
   championships: number
-  teamHistory: Schema.Types.ObjectId[]
+  teamHistory: Object[]
```
Comment (in-a-iii) [inline typings/model.d.ts:157]: great work!

**Review by in-a-iii — APPROVED** [review]
